### ISSUE TITLE
Require tuples to have specific tuples names

### ISSUE THREAD

**Issue by Avarel** [Avarel/Kaiper#8]
This is a pretty controversial change. This will lead to several complications yet this will also lead to a better implementation.

## Complications:
* **High inconvenience** for the end user, every parameters (as tuples are the only argument in invocation) will require a name. This means something like `println str: "hello"` or `Math.sin x: 2`. 
  * However, if applicable library functions can be designed around this with the coming of Multimethods which will be discussed in the pros section, like `print ln: "str"` `print f: "%d", items: [2]`.

## Pros:
* **Multimethods** will be 6 million times easier to implement. Multiple overrides can be done easy and even have the same argument number but different names.
  * `def function(what)` would be invoked like ``function what: "hello"``
  * `def function(why)` would be invoked like ``function why: "there"``
  * Both can have completely different implementations.
* VM implementation for tuples and destructuring would also be easier, as explicit parameter names means no rest patterns. @adriantodt 
* Prevents bugs and misinterpretation during scripting.

## Steps
- [x] Change the compiler.
- [x] Change patterns.
- [ ] Draft the multimethods system.

**Comment by adriantodt** [comment]
After thinking a bit, I approve this change. This would help me with the bytecode (due the way they're weakly serialized) and would let some rather "cool" features like `print f: "%n"` and `print ln: "str"`.

**Comment by adriantodt** [comment]
Yes, please.

**Comment by Avarel** [comment]
There's several logistical stuff I must do first, but I'm probably 70% commited to this change.

**Comment by Avarel** [comment]
Nope, this change has been reverted.
