### ISSUE TITLE
Custom language syntax highlighting for IntelliJ, Atom, or VSCode

### ISSUE THREAD

**Issue by Avarel** [Avarel/Kaiper#9]
Creation of a simple syntax highlighting plugin for the language experiment in any of these three platforms would be appreciated. Currently the actively developed branch is `features/tuples-neo`.

**Comment by rodol-fo** [comment]
I  think I can help with this, specifically with the IntelliJ plugin/syntax highlighter. Any guidelines to follow?

**Comment by Avarel** [comment]
@rodol-fo Develop on the features/tuples-neo branch. Code completion is desired but not required. All we’re looking for right now is the syntax highlighter.
